pragma foreign_keys = on;

CREATE TABLE user (
	username varchar(30) primary key,
	first_name varchar(30),
	last_name varchar(30),
	email varchar(320),
	password text
);

CREATE TABLE book (
	id integer primary key,
	owner varchar(30),
	title text,
	author text,
	year integer,
	foreign key (owner) references user(username)
);

CREATE TABLE user_token (
	username varchar(30) references user(username),
	token varchar(30),
	primary key(username, token)
);

CREATE TABLE loan (
	id integer primary key,
	book integer,
	recipient varchar(30),
	start date,
	span integer,
	status integer, -- 0: waiting, 1: rejected, 2: accepted, 3: finished
	foreign key(recipient) references user(username),
	foreign key(book) references book(id)
);

insert into user (username, first_name, last_name, email, password) values ("user1", "user", "one", "user1@yopmail.com", "$2b$12$eOvhl/Fo1VmU16Jt.lDqVuOvhywRZTkrt1ZoPvmDPRv6W2xDlb.F2");
insert into user (username, first_name, last_name, email, password) values ("user2", "user", "two", "user2@yopmail.com", "$2b$12$eOvhl/Fo1VmU16Jt.lDqVuOvhywRZTkrt1ZoPvmDPRv6W2xDlb.F2");

insert into book (owner, title, author, year) values ("user1", "Harry Potter and the Half-Blood Prince (Harry Potter  #6)", "J.K. Rowling/Mary GrandPré", 2006);
insert into book (owner, title, author, year) values ("user1", "Harry Potter and the Order of the Phoenix (Harry Potter  #5)", "J.K. Rowling/Mary GrandPré", 2004);
insert into book (owner, title, author, year) values ("user1", "Harry Potter and the Chamber of Secrets (Harry Potter  #2)", "J.K. Rowling", 2003);
insert into book (owner, title, author, year) values ("user2", "Harry Potter and the Prisoner of Azkaban (Harry Potter  #3)", "J.K. Rowling/Mary GrandPré", 2004);
insert into book (owner, title, author, year) values ("user2", "Harry Potter Boxed Set  Books 1-5 (Harry Potter  #1-5)", "J.K. Rowling/Mary GrandPré", 2004);
insert into book (owner, title, author, year) values ("user1", "Harry Potter Collection (Harry Potter  #1-6)", "J.K. Rowling", 2005);
insert into book (owner, title, author, year) values ("user1", "The Ultimate Hitchhiker's Guide: Five Complete Novels and One Story (Hitchhiker's Guide to the Galaxy  #1-5)", "Douglas Adams", 2005);
insert into book (owner, title, author, year) values ("user2", "The Ultimate Hitchhiker's Guide to the Galaxy (Hitchhiker's Guide to the Galaxy  #1-5)", "Douglas Adams", 2002);
insert into book (owner, title, author, year) values ("user2", "The Hitchhiker's Guide to the Galaxy (Hitchhiker's Guide to the Galaxy  #1)", "Douglas Adams", 2004);
insert into book (owner, title, author, year) values ("user2", "The Hitchhiker's Guide to the Galaxy (Hitchhiker's Guide to the Galaxy  #1)", "Douglas Adams/Stephen Fry", 2005);
insert into book (owner, title, author, year) values ("user1", "The Ultimate Hitchhiker's Guide (Hitchhiker's Guide to the Galaxy  #1-5)", "Douglas Adams", 1996);
insert into book (owner, title, author, year) values ("user2", "A Short History of Nearly Everything", "Bill Bryson", 2004);
insert into book (owner, title, author, year) values ("user1", "Bill Bryson's African Diary", "Bill Bryson", 2002);
insert into book (owner, title, author, year) values ("user2", "Bryson's Dictionary of Troublesome Words: A Writer's Guide to Getting It Right", "Bill Bryson", 2004);
insert into book (owner, title, author, year) values ("user1", "In a Sunburned Country", "Bill Bryson", 2001);
insert into book (owner, title, author, year) values ("user2", "I'm a Stranger Here Myself: Notes on Returning to America After Twenty Years Away", "Bill Bryson", 2000);
insert into book (owner, title, author, year) values ("user1", "The Lost Continent: Travels in Small Town America", "Bill Bryson", 1990);
insert into book (owner, title, author, year) values ("user2", "Neither Here nor There: Travels in Europe", "Bill Bryson", 1993);
insert into book (owner, title, author, year) values ("user1", "Notes from a Small Island", "Bill Bryson", 1997);
insert into book (owner, title, author, year) values ("user2", "The Mother Tongue: English and How It Got That Way", "Bill Bryson", 1991);
insert into book (owner, title, author, year) values ("user2", "J.R.R. Tolkien 4-Book Boxed Set: The Hobbit and The Lord of the Rings", "J.R.R. Tolkien", 2012);
insert into book (owner, title, author, year) values ("user2", "The Lord of the Rings (The Lord of the Rings  #1-3)", "J.R.R. Tolkien", 2004);
insert into book (owner, title, author, year) values ("user2", "The Fellowship of the Ring (The Lord of the Rings  #1)", "J.R.R. Tolkien", 2003);
insert into book (owner, title, author, year) values ("user1", "The Lord of the Rings (The Lord of the Rings  #1-3)", "J.R.R. Tolkien/Alan  Lee", 2002);
insert into book (owner, title, author, year) values ("user2", "The Lord of the Rings: Weapons and Warfare", "Chris   Smith/Christopher  Lee/Richard Taylor", 2003);
insert into book (owner, title, author, year) values ("user1", "The Lord of the Rings: Complete Visual Companion", "Jude Fisher", 2004);
insert into book (owner, title, author, year) values ("user2", "Agile Web Development with Rails: A Pragmatic Guide", "Dave Thomas/David Heinemeier Hansson/Leon Breedt/Mike Clark/Thomas  Fuchs/Andreas  Schwarz", 2005);
insert into book (owner, title, author, year) values ("user2", "Hatchet (Brian's Saga  #1)", "Gary Paulsen", 2000);
insert into book (owner, title, author, year) values ("user2", "Guts: The True Stories behind Hatchet and the Brian Books", "Gary Paulsen", 2001);
insert into book (owner, title, author, year) values ("user2", "Molly Hatchet - 5 of the Best", "Molly Hatchet", 2003);
insert into book (owner, title, author, year) values ("user2", "Hatchet Jobs: Writings on Contemporary Fiction", "Dale Peck", 2005);
insert into book (owner, title, author, year) values ("user1", "A Changeling for All Seasons (Changeling Seasons #1)", "Angela Knight/Sahara Kelly/Judy Mays/Marteeka Karland/Kate Douglas/Shelby Morgen/Lacey Savage/Kate Hill/Willa Okati", 2005);
insert into book (owner, title, author, year) values ("user2", "Changeling (Changeling  #1)", "Delia Sherman", 2006);
insert into book (owner, title, author, year) values ("user2", "The Changeling Sea", "Patricia A. McKillip", 2003);
insert into book (owner, title, author, year) values ("user2", "The Changeling", "Zilpha Keatley Snyder", 2004);
insert into book (owner, title, author, year) values ("user2", "The Changeling", "Kate Horsley", 2005);
insert into book (owner, title, author, year) values ("user2", "The Changeling (Daughters of England  #15)", "Philippa Carr", 1990);
insert into book (owner, title, author, year) values ("user2", "The Known World", "Edward P. Jones", 2006);
insert into book (owner, title, author, year) values ("user1", "The Known World", "Edward P. Jones/Kevin R. Free", 2004);
insert into book (owner, title, author, year) values ("user1", "The Known World", "Edward P. Jones", 2004);
insert into book (owner, title, author, year) values ("user1", "Traders  Guns & Money: Knowns and Unknowns in the Dazzling World of Derivatives", "Satyajit Das", 2006);
insert into book (owner, title, author, year) values ("user2", "Artesia: Adventures in the Known World", "Mark Smylie", 2005);
insert into book (owner, title, author, year) values ("user2", "The John McPhee Reader (John McPhee Reader  #1)", "John McPhee/William Howarth", 1982);
insert into book (owner, title, author, year) values ("user1", "Uncommon Carriers", "John McPhee", 2006);
insert into book (owner, title, author, year) values ("user2", "Heirs of General Practice", "John McPhee", 1986);
insert into book (owner, title, author, year) values ("user2", "The Control of Nature", "John McPhee", 1990);
insert into book (owner, title, author, year) values ("user2", "Annals of the Former World", "John McPhee", 1999);
insert into book (owner, title, author, year) values ("user1", "Coming Into the Country", "John McPhee", 1991);
insert into book (owner, title, author, year) values ("user1", "La Place de la Concorde Suisse", "John McPhee", 1994);
insert into book (owner, title, author, year) values ("user1", "Giving Good Weight", "John McPhee", 1994);
insert into book (owner, title, author, year) values ("user1", "Rising from the Plains", "John McPhee", 1987);
insert into book (owner, title, author, year) values ("user2", "The Heidi Chronicles", "Wendy Wasserstein", 2002);
insert into book (owner, title, author, year) values ("user1", "The Heidi Chronicles: Uncommon Women and Others & Isn't It Romantic", "Wendy Wasserstein", 1991);
insert into book (owner, title, author, year) values ("user1", "Active Literacy Across the Curriculum: Strategies for Reading  Writing  Speaking  and Listening", "Heidi Hayes Jacobs", 2006);
insert into book (owner, title, author, year) values ("user2", "Simply Beautiful Beaded Jewelry", "Heidi Boyd", 2006);
insert into book (owner, title, author, year) values ("user2", "Always Enough: God's Miraculous Provision Among the Poorest Children on Earth", "Heidi Baker/Rolland Baker", 2003);
insert into book (owner, title, author, year) values ("user1", "Mapping the Big Picture: Integrating Curriculum & Assessment K-12", "Heidi Hayes Jacobs", 1997);
insert into book (owner, title, author, year) values ("user1", "Heidi (Heidi  #1-2)", "Johanna Spyri/Beverly Cleary/Angelo  Rinaldi", 2002);
insert into book (owner, title, author, year) values ("user2", "Getting Results with Curriculum Mapping", "Heidi Hayes Jacobs", 2004);
insert into book (owner, title, author, year) values ("user1", "There's Always Enough: The Miraculous Move of God in Mozambique", "Rolland Baker/Heidi Baker", 2003);
insert into book (owner, title, author, year) values ("user2", "What to Expect the First Year (What to Expect)", "Heidi Murkoff/Sharon Mazel/Arlene Eisenberg/Sandee Hathaway/Mark D. Widome", 2003);
insert into book (owner, title, author, year) values ("user1", "The Player's Handbook: The Ultimate Guide on Dating and Relationships", "Heidi Fleiss/Libby Keatinge", 2004);
insert into book (owner, title, author, year) values ("user2", "Simply Beautiful Beading: 53 Quick and Easy Projects", "Heidi Boyd", 2004);
insert into book (owner, title, author, year) values ("user2", "God Emperor of Dune (Dune Chronicles  #4)", "Frank Herbert", 1987);
insert into book (owner, title, author, year) values ("user2", "Chapterhouse: Dune (Dune Chronicles #6)", "Frank Herbert", 1987);
insert into book (owner, title, author, year) values ("user1", "Dune Messiah (Dune Chronicles #2)", "Frank Herbert", 1987);
insert into book (owner, title, author, year) values ("user2", "Dreamer of Dune: The Biography of Frank Herbert", "Brian Herbert", 2004);
insert into book (owner, title, author, year) values ("user1", "Heretics of Dune (Dune Chronicles  #5)", "Frank Herbert", 1984);
insert into book (owner, title, author, year) values ("user2", "The Road to Dune", "Frank Herbert/Brian Herbert/Kevin J. Anderson", 2006);
insert into book (owner, title, author, year) values ("user1", "Heretics of Dune (Dune Chronicles #5)", "Frank Herbert", 1987);
insert into book (owner, title, author, year) values ("user2", "The Lord of the Rings: The Art of the Fellowship of the Ring", "Gary Russell", 2002);
insert into book (owner, title, author, year) values ("user2", "The Power of One (The Power of One  #1)", "Bryce Courtenay", 1996);
insert into book (owner, title, author, year) values ("user2", "The Power of One (The Power of One  #1)", "Bryce Courtenay", 2005);
insert into book (owner, title, author, year) values ("user2", "The Power of One: One Person  One Rule  One Month", "John C. Maxwell/Stephen R. Graves/Thomas G. Addington", 2004);
insert into book (owner, title, author, year) values ("user1", "Power of an Hour: Business and Life Mastery in One Hour a Week", "Dave Lakhani", 2006);
insert into book (owner, title, author, year) values ("user1", "The Power of One: The Solo Play for Playwrights  Actors  and Directors", "Louis E. Catron", 2000);
insert into book (owner, title, author, year) values ("user1", "How to Buy  Sell & Profit on eBay: Kick-Start Your Home-Based Business in Just Thirty Days", "Adam Ginsberg", 2005);
insert into book (owner, title, author, year) values ("user1", "eBay for Dummies", "Marsha Collier", 2006);
insert into book (owner, title, author, year) values ("user2", "What to Sell on ebay and Where to Get It: The Definitive Guide to Product Sourcing for eBay and Beyond", "Chris Malta/Lisa Suttora", 2006);
insert into book (owner, title, author, year) values ("user2", "Starting an eBay Business for Dummies", "Marsha Collier", 2004);
insert into book (owner, title, author, year) values ("user2", "eBay: Top 100 Simplified Tips & Tricks", "Julia Wilkinson", 2006);
insert into book (owner, title, author, year) values ("user2", "ebay Timesaving Techniques for Dummies", "Marsha Collier", 2004);
insert into book (owner, title, author, year) values ("user1", "eBay Business All-in-One Desk Reference for Dummies", "Marsha Collier", 2005);
insert into book (owner, title, author, year) values ("user1", "Ruby Cookbook", "Lucas Carlson/Leonard Richardson", 2006);
insert into book (owner, title, author, year) values ("user1", "Ruby Ann's Down Home Trailer Park Cookbook", "Ruby Ann Boxcar", 2005);
insert into book (owner, title, author, year) values ("user1", "Ruby Ann's Down Home Trailer Park BBQin' Cookbook", "Ruby Ann Boxcar", 2005);
insert into book (owner, title, author, year) values ("user2", "Rails Cookbook: Recipes for Rapid Web Development with Ruby", "Rob Orsini", 2007);
insert into book (owner, title, author, year) values ("user1", "Anna Karenina", "Leo Tolstoy/Richard Pevear/Larissa Volokhonsky", 2004);
insert into book (owner, title, author, year) values ("user1", "Anna Karenina", "Leo Tolstoy/David Magarshack/Priscilla Meyer", 2002);
insert into book (owner, title, author, year) values ("user1", "Anna Karenina", "Leo Tolstoy/Richard Pevear/Larissa Volokhonsky/John Bayley", 2003);
insert into book (owner, title, author, year) values ("user1", "CliffsNotes on Tolstoy's Anna Karenina", "Marianne Sturman/Leo Tolstoy", 1965);
insert into book (owner, title, author, year) values ("user1", "Anna Karenina", "Leo Tolstoy/Amy Mandelker/Constance Garnett", 2003);
insert into book (owner, title, author, year) values ("user2", "Anna Karenina", "Leo Tolstoy/Louise Maude/Aylmer Maude", 2004);
insert into book (owner, title, author, year) values ("user2", "Anna Karenina", "Leo Tolstoy/Constance Garnett/Amy Mandelker", 2004);
insert into book (owner, title, author, year) values ("user1", "Dinner with Anna Karenina", "Gloria Goldreich", 2006);
insert into book (owner, title, author, year) values ("user1", "Tolstoy: Anna Karenina", "Anthony Thorlby", 1987);
insert into book (owner, title, author, year) values ("user2", "Untouchable", "Mulk Raj Anand/E.M. Forster", 1990);
insert into book (owner, title, author, year) values ("user1", "The Untouchable", "John Banville", 1998);
insert into book (owner, title, author, year) values ("user1", "The Untouchables", "Eliot Ness/Oscar Fraley", 1996);
insert into book (owner, title, author, year) values ("user2", "Untouchables: My Family's Triumphant Journey Out of the Caste System in Modern India", "Narendra Jadhav", 2005);
insert into book (owner, title, author, year) values ("user2", "Dalit: The Black Untaouchables of India", "V.T. Rajshekar/Y.N. Kly", 1995);
insert into book (owner, title, author, year) values ("user1", "Growing Up Untouchable in India: A Dalit Autobiography", "Vasant Moon/Gail Omvedt/Eleanor Zelliot", 2000);
insert into book (owner, title, author, year) values ("user1", "The Evidence-Based Social Work Skills Book", "Barry R. Cournoyer", 2003);
insert into book (owner, title, author, year) values ("user2", "Wrinkles in Time", "George Smoot/Keay Davidson", 1994);
insert into book (owner, title, author, year) values ("user1", "A Wrinkle in Time: With Related Readings (A Wrinkle in Time Quintet #1)", "Madeleine L'Engle", 2002);
insert into book (owner, title, author, year) values ("user2", "Literature Circle Guide: A Wrinkle in Time", "Tara MacCarthy", 2002);
insert into book (owner, title, author, year) values ("user1", "Una arruga en el tiempo – A Wrinkle in Time", "Madeleine L'Engle", 1984);
insert into book (owner, title, author, year) values ("user1", "The Long Shadow (The Morland Dynasty  #6)", "Cynthia Harrod-Eagles", 1994);
insert into book (owner, title, author, year) values ("user2", "A Long Shadow (Inspector Ian Rutledge  #8)", "Charles Todd", 2006);
insert into book (owner, title, author, year) values ("user2", "Long Way Round: Chasing Shadows Across the World", "Ewan McGregor/Charley Boorman/Robert Uhlig", 2005);
insert into book (owner, title, author, year) values ("user2", "A Shadow in Summer (Long Price Quartet  #1)", "Daniel Abraham", 2006);
insert into book (owner, title, author, year) values ("user1", "New Hope for the Dead (Hoke Mosely #2)", "Charles Willeford/James Lee Burke", 2004);
insert into book (owner, title, author, year) values ("user1", "Sideswipe: A Hoke Moseley Novel", "Charles Willeford/Lawrence Block", 2005);
insert into book (owner, title, author, year) values ("user2", "Miami Blues (Hoke Moseley #1)", "Charles Willeford/Elmore Leonard", 2004);
insert into book (owner, title, author, year) values ("user1", "The Burnt Orange Heresy (Vintage Crime/Black Lizard)", "Charles Willeford", 1990);
insert into book (owner, title, author, year) values ("user2", "I am Charlotte Simmons", "Tom Wolfe", 2005);
insert into book (owner, title, author, year) values ("user2", "Poetry for Young People: Edward Lear", "Edward Lear/Laura Huliska-Beith/Edward Mendelson", 2001);
insert into book (owner, title, author, year) values ("user1", "The Puffin Book of Nonsense Verse", "Quentin Blake", 1996);
insert into book (owner, title, author, year) values ("user2", "Henry Miller on Writing", "Henry Miller/Thomas H. Moore", 1964);
insert into book (owner, title, author, year) values ("user2", "Quiet Days in Clichy", "Henry Miller", 1994);
insert into book (owner, title, author, year) values ("user2", "Tropic of Cancer", "Henry Miller/Jiří Níl", 1994);
insert into book (owner, title, author, year) values ("user1", "Tropic of Capricorn", "Henry Miller", 1994);
insert into book (owner, title, author, year) values ("user2", "Nexus (The Rosy Crucifixion  #3)", "Henry Miller", 1994);
insert into book (owner, title, author, year) values ("user2", "Sexus (The Rosy Crucifixion  #1)", "Henry Miller", 1994);
insert into book (owner, title, author, year) values ("user2", "The Air-Conditioned Nightmare", "Henry Miller", 1970);
insert into book (owner, title, author, year) values ("user1", "The Portrait of a Lady", "Henry James/Patricia Crick", 2003);
insert into book (owner, title, author, year) values ("user1", "The Portrait of a Lady", "Henry James/Gabriel Brownstein/Mary Cregan", 2004);
insert into book (owner, title, author, year) values ("user1", "Writing", "Marguerite Duras", 1999);
insert into book (owner, title, author, year) values ("user1", "The War", "Marguerite Duras/Barbara Bray", 1994);
insert into book (owner, title, author, year) values ("user2", "The Ravishing of Lol Stein", "Marguerite Duras/Richard Seever", 1986);
insert into book (owner, title, author, year) values ("user1", "Love Letters", "Kahlil Gibran/Suheil Bushrui/Salma H. Al-Kuzbari", 1999);
insert into book (owner, title, author, year) values ("user1", "Kahlil Gibran: His Life and World", "Jean Gibran/جبران خليل جبران/Kahlil Gibran", 1998);
insert into book (owner, title, author, year) values ("user2", "The Beloved: Reflections on the Path of the Heart", "Kahlil Gibran/John Walbridge/Robin Waterfield", 1998);
insert into book (owner, title, author, year) values ("user2", "Jesus the Son of Man", "Kahlil Gibran/جبران خليل جبران", 1995);
insert into book (owner, title, author, year) values ("user1", "The Broken Wings", "Kahlil Gibran/جبران خليل جبران/Anthony Rizcallah Ferris", 2003);
insert into book (owner, title, author, year) values ("user2", "Sand and Foam", "Kahlil Gibran/جبران خليل جبران", 2011);
insert into book (owner, title, author, year) values ("user1", "Treasure Island", "Robert Louis Stevenson", 2001);
insert into book (owner, title, author, year) values ("user2", "Treasure Island", "Robert Louis Stevenson/Scott McKowen", 2004);
insert into book (owner, title, author, year) values ("user2", "Treasure Island", "Robert Louis Stevenson", 2005);
insert into book (owner, title, author, year) values ("user1", "Treasure Island", "Robert Louis Stevenson/N.C. Wyeth/Timothy Meis", 2003);
insert into book (owner, title, author, year) values ("user2", "Treasure Island", "Robert Louis Stevenson/Milo Winter", 2002);
insert into book (owner, title, author, year) values ("user2", "Treasure Island (Great Illustrated Classics)", "Deidre S. Laiken/A.J. McAllister/Robert Louis Stevenson", 2006);
insert into book (owner, title, author, year) values ("user2", "100 Years of Lynchings", "Ralph Ginzburg", 1996);
insert into book (owner, title, author, year) values ("user2", "Cien años de soledad", "Gabriel García Márquez", 1990);
insert into book (owner, title, author, year) values ("user2", "On Beyond Zebra!", "Dr. Seuss", 1955);
insert into book (owner, title, author, year) values ("user2", "The Wedding Clause", "Debbie Raleigh", 2005);
insert into book (owner, title, author, year) values ("user1", "The Zebra Wall", "Kevin Henkes", 2005);
insert into book (owner, title, author, year) values ("user2", "El perfume: Historia de un asesino", "Patrick Süskind", 2002);
insert into book (owner, title, author, year) values ("user2", "The Door Into Summer", "Robert A. Heinlein", 1997);
insert into book (owner, title, author, year) values ("user2", "Stranger in a Strange Land", "Robert A. Heinlein", 1991);
insert into book (owner, title, author, year) values ("user1", "To Sail Beyond the Sunset", "Robert A. Heinlein", 1988);
insert into book (owner, title, author, year) values ("user2", "Job: A Comedy of Justice", "Robert A. Heinlein", 1985);
insert into book (owner, title, author, year) values ("user1", "Time for the Stars (Heinlein's Juveniles  #10)", "Robert A. Heinlein", 2006);
insert into book (owner, title, author, year) values ("user1", "The Long Dark Tea-Time of the Soul (Dirk Gently  #2)", "Douglas Adams", 1991);
insert into book (owner, title, author, year) values ("user1", "The Salmon of Doubt (Dirk Gently  #3)", "Douglas Adams", 2005);
insert into book (owner, title, author, year) values ("user2", "Wish You Were Here: The Official Biography of Douglas Adams", "Nick  Webb", 2005);
insert into book (owner, title, author, year) values ("user1", "Douglas Adams's Starship Titanic", "Terry Jones", 1998);
insert into book (owner, title, author, year) values ("user1", "Salmon of Doubt: Hitchhiking the Galaxy One Last Time", "Douglas Adams/Christopher Cerf", 2003);
insert into book (owner, title, author, year) values ("user1", "The Phantom Tollbooth: A Children's Play in Two Acts", "Susan Nanus/Norton Juster", 2011);
insert into book (owner, title, author, year) values ("user2", "On Bullshit", "Harry G. Frankfurt", 2005);
insert into book (owner, title, author, year) values ("user1", "Another Bullshit Night in Suck City", "Nick Flynn", 2005);
insert into book (owner, title, author, year) values ("user1", "Lincoln at Gettysburg: The Words That Remade America", "Garry Wills", 1993);
insert into book (owner, title, author, year) values ("user2", "The Gettysburg Address", "Abraham Lincoln/Michael McCurdy", 1998);
insert into book (owner, title, author, year) values ("user2", "Underworld", "Don DeLillo", 1998);
insert into book (owner, title, author, year) values ("user2", "Libra", "Don DeLillo", 1991);
insert into book (owner, title, author, year) values ("user1", "Americana", "Don DeLillo", 1989);
insert into book (owner, title, author, year) values ("user1", "Running Dog", "Don DeLillo", 1989);
insert into book (owner, title, author, year) values ("user1", "Cosmopolis", "Don DeLillo", 2004);
insert into book (owner, title, author, year) values ("user2", "Great Jones Street", "Don DeLillo", 1994);
insert into book (owner, title, author, year) values ("user1", "The Names", "Don DeLillo", 1989);
insert into book (owner, title, author, year) values ("user1", "Against the Day", "Thomas Pynchon", 2006);
insert into book (owner, title, author, year) values ("user2", "V.", "Thomas Pynchon", 2005);
insert into book (owner, title, author, year) values ("user2", "The Crying of Lot 49", "Thomas Pynchon", 1999);
insert into book (owner, title, author, year) values ("user2", "Gravity's Rainbow", "Thomas Pynchon", 2000);
insert into book (owner, title, author, year) values ("user1", "Mason & Dixon", "Thomas Pynchon/Christophe Claro/Brice Matthieussent", 2004);
insert into book (owner, title, author, year) values ("user2", "Vineland", "Thomas Pynchon", 1997);
insert into book (owner, title, author, year) values ("user2", "Gravity's Rainbow", "Thomas Pynchon", 2006);
insert into book (owner, title, author, year) values ("user2", "Slow Learner: Early Stories", "Thomas Pynchon", 1985);
insert into book (owner, title, author, year) values ("user1", "Been Down So Long It Looks Like Up To Me", "Richard Fariña/Thomas Pynchon", 1996);
insert into book (owner, title, author, year) values ("user1", "The Year of Magical Thinking", "Joan Didion", 2005);
insert into book (owner, title, author, year) values ("user1", "The White Album", "Joan Didion", 1990);
insert into book (owner, title, author, year) values ("user2", "A Book of Common Prayer", "Joan Didion", 1995);
insert into book (owner, title, author, year) values ("user1", "Where I Was From", "Joan Didion", 2004);
insert into book (owner, title, author, year) values ("user1", "Slouching Towards Bethlehem", "Joan Didion", 1990);
insert into book (owner, title, author, year) values ("user2", "Democracy", "Joan Didion", 1995);
insert into book (owner, title, author, year) values ("user2", "We Tell Ourselves Stories in Order to Live: Collected Nonfiction", "Joan Didion/John Leonard", 2006);
insert into book (owner, title, author, year) values ("user2", "Play It As It Lays", "Joan Didion/David Thomson", 2005);
insert into book (owner, title, author, year) values ("user1", "The New York Trilogy", "Paul Auster/Art Spiegelman/Luc Sante", 2006);
insert into book (owner, title, author, year) values ("user1", "City of Glass (The New York Trilogy  #1)", "Paul Auster", 1987);
insert into book (owner, title, author, year) values ("user2", "Ghosts (The New York Trilogy  #2)", "Paul Auster", 1987);
insert into book (owner, title, author, year) values ("user2", "The Locked Room (The New York Trilogy  #3)", "Paul Auster", 1986);
insert into book (owner, title, author, year) values ("user2", "Pyramids of Montauk: Explorations in Consciousness", "Peter Moon/Preston B. Nichols/Nina Helms", 1995);
insert into book (owner, title, author, year) values ("user1", "The Brooklyn Follies", "Paul Auster", 2006);
insert into book (owner, title, author, year) values ("user2", "Moon Palace", "Paul Auster", 1990);
insert into book (owner, title, author, year) values ("user2", "The Music of Chance", "Paul Auster", 1991);
insert into book (owner, title, author, year) values ("user2", "Travels in the Scriptorium", "Paul Auster", 2007);
insert into book (owner, title, author, year) values ("user1", "Leviathan", "Paul Auster", 1993);
insert into book (owner, title, author, year) values ("user1", "The Red Notebook: True Stories", "Paul Auster", 2002);
insert into book (owner, title, author, year) values ("user2", "Timbuktu / Leviathan / Moon Palace", "Paul Auster", 2002);
insert into book (owner, title, author, year) values ("user2", "Collapse: How Societies Choose to Fail or Succeed", "Jared Diamond", 2005);
insert into book (owner, title, author, year) values ("user2", "The Coming Economic Collapse: How You Can Thrive When Oil Costs $200 a Barrel", "Stephen Leeb/Glen C. Strathy", 2006);
insert into book (owner, title, author, year) values ("user1", "Collapse of Complex Societies", "Joseph A. Tainter", 1990);
insert into book (owner, title, author, year) values ("user1", "Bowling Alone: The Collapse and Revival of American Community", "Robert D. Putnam", 2001);
insert into book (owner, title, author, year) values ("user1", "The Collapse of the Common Good: How America's Lawsuit Culture Undermines Our Freedom", "Philip K. Howard", 2002);
insert into book (owner, title, author, year) values ("user2", "Reinventing the Enemy's Language: Contemporary Native Women's Writings of North America", "Joy Harjo/Gloria Bird/Beth Cuthand/Valerie Martinez/Patricia Blanco", 1998);
insert into book (owner, title, author, year) values ("user1", "My Inventions", "Nikola Tesla", 2006);
insert into book (owner, title, author, year) values ("user1", "Wizard: The Life and Times of Nikola Tesla: Biography of a Genius", "Marc J.  Seifer/William H. Terbo", 2001);
insert into book (owner, title, author, year) values ("user1", "Nikola Tesla: A Spark of Genius", "Carol Dommermuth-Costa", 1994);
insert into book (owner, title, author, year) values ("user2", "Tesla Papers", "Nikola Tesla/David Hatcher Childress", 2000);
insert into book (owner, title, author, year) values ("user1", "Boys of Summer", "Julie Elizabeth Leto/Leslie Kelly/Kimberly Raye", 2006);
insert into book (owner, title, author, year) values ("user2", "Programming Ruby: The Pragmatic Programmers' Guide", "Dave Thomas/Chad Fowler/Andy Hunt", 2004);
insert into book (owner, title, author, year) values ("user1", "Golding's Lord of the Flies (Cliffs Notes)", "Maureen Kelly/CliffsNotes/William Golding", 2000);
insert into book (owner, title, author, year) values ("user2", "Lord of the Flies", "William Golding", 2005);
insert into book (owner, title, author, year) values ("user1", "A War Like No Other: How the Athenians & Spartans Fought the Peloponnesian War", "Victor Davis Hanson", 2006);
insert into book (owner, title, author, year) values ("user2", "We Were Not Like Other People", "Ephraim Sevela/Antonina W. Bouis", 1989);
insert into book (owner, title, author, year) values ("user2", "The Lovely Bones", "Alice Sebold", 2003);
insert into book (owner, title, author, year) values ("user1", "The Lovely Bones", "Alice Sebold", 2004);
insert into book (owner, title, author, year) values ("user2", "Lovely in Her Bones (Elizabeth MacPherson  #2)", "Sharyn McCrumb", 1990);
insert into book (owner, title, author, year) values ("user1", "The Zen of CSS Design: Visual Enlightenment for the Web", "Dave Shea/Molly E. Holzschlag", 2005);
insert into book (owner, title, author, year) values ("user1", "HTML  XHTML  and CSS (Visual Quickstart Guide)", "Elizabeth Castro", 2006);
insert into book (owner, title, author, year) values ("user1", "1000 Record Covers", "Michael Ochs/Patrick Javault/Ulrike Wasel", 2005);
insert into book (owner, title, author, year) values ("user1", "Killing Yourself to Live: 85% of a True Story", "Chuck Klosterman", 2006);
insert into book (owner, title, author, year) values ("user2", "Sex  Drugs  and Cocoa Puffs: A Low Culture Manifesto", "Chuck Klosterman", 2004);
insert into book (owner, title, author, year) values ("user2", "Vice (V  #8)", "Jane Feather", 1996);
insert into book (owner, title, author, year) values ("user2", "Zen and the Art of Motorcycle Maintenance: An Inquiry Into Values (Phaedrus  #1)", "Robert M. Pirsig", 2006);
insert into book (owner, title, author, year) values ("user1", "Once Upon a Cool Motorcycle Dude", "Kevin O'Malley/Carol Heyer/Scott Goto", 2005);
insert into book (owner, title, author, year) values ("user1", "Guidebook to Zen and the Art of Motorcycle Maintenance", "Ronald L. DiSanto/Thomas J. Steele", 1990);
insert into book (owner, title, author, year) values ("user1", "Motorcycle Basics Techbook", "John Harold Haynes", 2002);
insert into book (owner, title, author, year) values ("user1", "LOGO Lounge: 2 000 International Identities by Leading Designers", "Catharine M. Fishel/Bill Gardner", 2004);
insert into book (owner, title, author, year) values ("user1", "The Death of Ivan Ilych And Other Stories", "Leo Tolstoy/Hugh McLean", 2003);
insert into book (owner, title, author, year) values ("user1", "War and Peace", "Leo Tolstoy/Henry Gifford/Aylmer Maude/Louise Maude", 1998);
insert into book (owner, title, author, year) values ("user1", "The Kingdom of God Is Within You", "Leo Tolstoy/Constance Garnett", 2006);
insert into book (owner, title, author, year) values ("user2", "Atlas Shrugged", "Ayn Rand/Leonard Peikoff", 1999);
insert into book (owner, title, author, year) values ("user1", "For the New Intellectual: The Philosophy of Ayn Rand", "Ayn Rand", 1963);
insert into book (owner, title, author, year) values ("user1", "The Fountainhead", "Ayn Rand", 2005);
insert into book (owner, title, author, year) values ("user1", "The Virtue of Selfishness: A New Concept of Egoism", "Ayn Rand/Nathaniel Branden", 1964);
insert into book (owner, title, author, year) values ("user2", "Anthem", "Ayn Rand", 1999);
insert into book (owner, title, author, year) values ("user1", "We the Living", "Ayn Rand/Leonard Peikoff", 1996);
insert into book (owner, title, author, year) values ("user1", "Capitalism: The Unknown Ideal", "Ayn Rand/Nathaniel Branden/Alan Greenspan/Robert Hessen", 1986);
insert into book (owner, title, author, year) values ("user2", "Letters of Ayn Rand", "Ayn Rand/Michael S. Berliner/Leonard Peikoff", 1997);
insert into book (owner, title, author, year) values ("user1", "Sailing for Dummies", "J.J. Isler/Peter Isler", 2006);
insert into book (owner, title, author, year) values ("user2", "Sailing from Byzantium: How a Lost Empire Shaped the World", "Colin  Wells", 2006);
insert into book (owner, title, author, year) values ("user2", "Sailing Alone Around the Room: New and Selected Poems", "Billy Collins", 2002);
insert into book (owner, title, author, year) values ("user2", "The Greatest Sailing Stories Ever Told: Twenty-Seven Unforgettable Stories", "Christopher Caswell", 2004);
insert into book (owner, title, author, year) values ("user2", "The Natural", "Bernard Malamud/Kevin Baker", 2003);
insert into book (owner, title, author, year) values ("user1", "Digging to America", "Anne Tyler", 2006);
insert into book (owner, title, author, year) values ("user2", "Rereading America: Cultural Contexts for Critical Thinking and Writing", "Gary Colombo/Bonnie Lisle", 2004);
insert into book (owner, title, author, year) values ("user2", "Modern Latin America", "Thomas E. Skidmore/Peter H. Smith", 2004);
insert into book (owner, title, author, year) values ("user2", "The Plot Against America", "Philip Roth", 2005);
insert into book (owner, title, author, year) values ("user2", "Naked Pictures of Famous People", "Jon   Stewart", 1999);
insert into book (owner, title, author, year) values ("user1", "Collected Stories", "Gabriel García Márquez/Gregory Rabassa/J.S. Bernstein", 2008);
insert into book (owner, title, author, year) values ("user2", "Crónica de una muerte anunciada", "Gabriel García Márquez", 2003);
insert into book (owner, title, author, year) values ("user1", "Cien años de soledad", "Gabriel García Márquez", 2006);
insert into book (owner, title, author, year) values ("user2", "Del amor y otros demonios", "Gabriel García Márquez", 2006);
insert into book (owner, title, author, year) values ("user1", "Living to Tell the Tale", "Gabriel García Márquez/Edith Grossman", 2004);
insert into book (owner, title, author, year) values ("user1", "Memoria de mis putas tristes", "Gabriel García Márquez", 2004);
insert into book (owner, title, author, year) values ("user2", "The Elegant Universe: Superstrings  Hidden Dimensions  and the Quest for the Ultimate Theory", "Brian Greene", 2004);
insert into book (owner, title, author, year) values ("user2", "Pure and Simple: The Extraordinary Teachings of a Thai Buddhist Laywoman", "Upasika Kee Nanayon/Thanissaro Bhikkhu", 2005);
insert into book (owner, title, author, year) values ("user2", "The Mini Rough Guide to London", "Rob Humphreys/Beth Chaplin/Rebecca Morrill", 2006);
insert into book (owner, title, author, year) values ("user1", "Best of London (Lonely Planet Best Of)", "Lonely Planet/Sarah Johnstone/Steve Fallon", 2004);
insert into book (owner, title, author, year) values ("user1", "Lonely Planet Londres", "Lonely Planet/Sarah Johnstone/Tom Masters", 2006);
insert into book (owner, title, author, year) values ("user1", "Out to Eat London 2002 (Lonely Planet Out to Eat)", "Lonely Planet/Mark Honan", 2001);
insert into book (owner, title, author, year) values ("user2", "Three Nights in August: Strategy  Heartbreak  and Joy Inside the Mind of a Manager", "H.G. Bissinger", 2006);
insert into book (owner, title, author, year) values ("user2", "Cryptonomicon", "Neal Stephenson", 2002);
insert into book (owner, title, author, year) values ("user1", "Le Réseau Kinakuta (Cryptonomicon  #2)", "Neal Stephenson", 2001);
insert into book (owner, title, author, year) values ("user2", "The Confusion (The Baroque Cycle  #2)", "Neal Stephenson", 2005);
insert into book (owner, title, author, year) values ("user1", "Quicksilver (The Baroque Cycle  #1)", "Neal Stephenson", 2004);
insert into book (owner, title, author, year) values ("user2", "The Cobweb", "Neal Stephenson/J. Frederick George", 2005);
insert into book (owner, title, author, year) values ("user2", "The Big U", "Neal Stephenson", 2001);
insert into book (owner, title, author, year) values ("user1", "The Diamond Age: Or  A Young Lady's Illustrated Primer", "Neal Stephenson/Pedro Jorge Romero", 2000);
insert into book (owner, title, author, year) values ("user1", "Interface", "Neal Stephenson/George F. Jewsbury/Stephen  Bury", 2005);
insert into book (owner, title, author, year) values ("user1", "Odalisque (The Baroque Cycle  Vol. 1  Book 3)", "Neal Stephenson", 2006);
insert into book (owner, title, author, year) values ("user2", "Snow Crash", "Neal Stephenson/Guy Abadia", 2000);
insert into book (owner, title, author, year) values ("user1", "Harrington on Hold 'em: Expert Strategy for No-Limit Tournaments  Volume II: The Endgame", "Dan Harrington/Bill Robertie", 2005);
insert into book (owner, title, author, year) values ("user1", "Harrington on Hold 'em: Expert Strategy for No-Limit Tournaments  Volume I: Strategic Play", "Dan Harrington/Bill Robertie", 2004);
insert into book (owner, title, author, year) values ("user2", "The Design of Everyday Things", "Donald A. Norman", 2002);
insert into book (owner, title, author, year) values ("user2", "Emotional Design: Why We Love (or Hate) Everyday Things", "Donald A. Norman", 2005);
insert into book (owner, title, author, year) values ("user2", "The Psychology of Everyday Things", "Donald A. Norman", 1988);
insert into book (owner, title, author, year) values ("user1", "No Price Too High: A Pentecostal Preacher Becomes Catholic - The Inspirational Story of Alex Jones as Told to Diane Hanson", "Alex C. Jones/Diane M. Hanson/Stephen K. Ray", 2006);
insert into book (owner, title, author, year) values ("user2", "The Alchemist", "Paulo Coelho/Alan R. Clarke/James Noel Smith", 2006);
insert into book (owner, title, author, year) values ("user1", "The Alchemist", "Paulo Coelho/Alan R. Clarke/Özdemir İnce", 1993);
insert into book (owner, title, author, year) values ("user2", "Fullmetal Alchemist  Vol. 9 (Fullmetal Alchemist  #9)", "Hiromu Arakawa/Akira Watanabe", 2006);
insert into book (owner, title, author, year) values ("user1", "Fullmetal Alchemist  Vol. 3 (Fullmetal Alchemist  #3)", "Hiromu Arakawa/Akira Watanabe", 2005);
insert into book (owner, title, author, year) values ("user1", "Fullmetal Alchemist  Vol. 8 (Fullmetal Alchemist  #8)", "Hiromu Arakawa/Akira Watanabe", 2006);
insert into book (owner, title, author, year) values ("user1", "Fullmetal Alchemist  Vol. 1 (Fullmetal Alchemist  #1)", "Hiromu Arakawa/Akira Watanabe", 2005);
insert into book (owner, title, author, year) values ("user1", "Fullmetal Alchemist  Vol. 4 (Fullmetal Alchemist  #4)", "Hiromu Arakawa/Akira Watanabe", 2005);
insert into book (owner, title, author, year) values ("user2", "The Illustrated Alchemist: A Fable about Following Your Dream", "Paulo Coelho/Alan R. Clarke/Mœbius", 1998);
insert into book (owner, title, author, year) values ("user1", "Fullmetal Alchemist  Vol. 2 (Fullmetal Alchemist  #2)", "Hiromu Arakawa/Akira Watanabe", 2005);
insert into book (owner, title, author, year) values ("user1", "Pompeii", "Robert   Harris", 2005);
insert into book (owner, title, author, year) values ("user2", "The Last Days of Pompeii", "Edward Bulwer-Lytton/John Gregory Betancourt", 2002);
insert into book (owner, title, author, year) values ("user1", "Of Mice and Men", "John Steinbeck", 2002);
insert into book (owner, title, author, year) values ("user1", "The Game: Penetrating the Secret Society of Pickup Artists", "Neil Strauss", 2005);
insert into book (owner, title, author, year) values ("user1", "The Westing Game", "Ellen Raskin", 2004);
insert into book (owner, title, author, year) values ("user1", "The Egypt Game", "Zilpha Keatley Snyder", 2009);
insert into book (owner, title, author, year) values ("user1", "Memoirs of a Geisha", "Arthur Golden", 2005);
insert into book (owner, title, author, year) values ("user2", "Memoirs of a Geisha", "Arthur Golden", 2005);
insert into book (owner, title, author, year) values ("user1", "Memoirs of a Geisha", "Arthur Golden", 2005);
insert into book (owner, title, author, year) values ("user2", "Memoirs of a Geisha: A Portrait of the Film", "David        James/Peggy Mulloy/Rob Marshall/Arthur Golden", 2005);
insert into book (owner, title, author, year) values ("user1", "Memoirs of a Geisha", "Arthur Golden", 1998);
insert into book (owner, title, author, year) values ("user2", "Geisha of Gion", "Mineko Iwasaki/Rande Brown", 2003);
insert into book (owner, title, author, year) values ("user1", "Love As A Foreign Language #5", "J. Torres/Eric  Kim", 2006);
insert into book (owner, title, author, year) values ("user1", "Jungle Love", "Margaret Johnson/Philip Prowse", 2002);
insert into book (owner, title, author, year) values ("user2", "The 5 Love Languages / The 5 Love Languages Journal", "Gary Chapman", 2005);
insert into book (owner, title, author, year) values ("user1", "Angels & Demons (Robert Langdon  #1)", "Dan Brown", 2006);
insert into book (owner, title, author, year) values ("user2", "Ángeles y demonios (Robert Langdon  #1)", "Dan Brown", 2005);
insert into book (owner, title, author, year) values ("user2", "Angeles & Demonios", "Dan Brown/Raúl Amundaray", 2005);
insert into book (owner, title, author, year) values ("user1", "The Da Vinci Code (Robert Langdon  #2)", "Dan Brown", 2006);
insert into book (owner, title, author, year) values ("user1", "The Da Vinci Code", "Dan Brown", 2006);
insert into book (owner, title, author, year) values ("user2", "Da Vinci Code (Robert Langdon  #2)", "Dan Brown/Daniel Roche", 2005);
insert into book (owner, title, author, year) values ("user2", "Deception Point", "Dan Brown", 2006);
insert into book (owner, title, author, year) values ("user2", "Deception Point", "Dan Brown", 2004);
insert into book (owner, title, author, year) values ("user2", "Deception Point", "Dan Brown", 2005);
insert into book (owner, title, author, year) values ("user2", "A Killing Rain (Louis Kincaid  #6)", "P.J. Parrish", 2005);
insert into book (owner, title, author, year) values ("user1", "The Millionaire Next Door: The Surprising Secrets of America's Wealthy", "Thomas J. Stanley/William D. Danko", 1998);
insert into book (owner, title, author, year) values ("user2", "Think and Grow Rich: The Landmark Bestseller Now Revised and Updated for the 21st Century", "Napoleon Hill", 2005);
insert into book (owner, title, author, year) values ("user1", "Think and Grow Rich", "Napoleon Hill", 2004);
insert into book (owner, title, author, year) values ("user1", "Pragmatic Version Control: Using Subversion (The Pragmatic Starter Kit Series)", "Mike   Mason", 2006);
insert into book (owner, title, author, year) values ("user1", "Read My Lips: Sexual Subversion and the End of Gender", "Riki Anne Wilchins", 2005);
insert into book (owner, title, author, year) values ("user1", "Trump: The Art of the Deal", "Donald J. Trump/Tony Schwartz", 2004);
insert into book (owner, title, author, year) values ("user2", "The Richest Man in Babylon", "George S. Clason", 2008);
insert into book (owner, title, author, year) values ("user2", "The Richest Man in Babylon", "George S. Clason", 2005);
insert into book (owner, title, author, year) values ("user2", "Shibumi", "Trevanian/Gisela Stege", 2005);
insert into book (owner, title, author, year) values ("user2", "1776", "David McCullough", 2006);
insert into book (owner, title, author, year) values ("user1", "1776", "Peter  Stone/Sherman Edwards", 1976);
insert into book (owner, title, author, year) values ("user1", "The Crescent Obscured: The United States and the Muslim World  1776-1815", "Robert J. Allison", 2000);
insert into book (owner, title, author, year) values ("user1", "The Good Earth (House of Earth  #1)", "Pearl S. Buck", 2009);
insert into book (owner, title, author, year) values ("user1", "Purpose Driven Life - For Commuters: What on Earth Am I Here For?", "Rick Warren", 2005);
insert into book (owner, title, author, year) values ("user1", "Fast Food Nation: The Dark Side of the All-American Meal", "Eric Schlosser", 2005);
insert into book (owner, title, author, year) values ("user1", "Fast Food Nation: What The All-American Meal is Doing to the World", "Eric Schlosser", 2002);
insert into book (owner, title, author, year) values ("user1", "Snow Flower and the Secret Fan", "Lisa See", 2006);
insert into book (owner, title, author, year) values ("user1", "The Broker", "John Grisham", 2006);
insert into book (owner, title, author, year) values ("user1", "The Power Broker: Robert Moses and the Fall of New York", "Robert A. Caro", 1975);
insert into book (owner, title, author, year) values ("user1", "The Power Broker: A Novel (Christian Gillette  #3)", "Stephen W. Frey", 2006);
insert into book (owner, title, author, year) values ("user1", "Body For Life: 12 Weeks to Mental and Physical Strength", "Bill Phillips/Michael D'Orso", 1999);
insert into book (owner, title, author, year) values ("user1", "Body for Life for Women: A Woman's Plan for Physical and Mental Transformation", "Pamela Peeke/Cindy Crawford", 2005);
insert into book (owner, title, author, year) values ("user1", "Eating for Life: Your Guide to Great Health  Fat Loss and Increased Energy!", "Bill Phillips", 2003);
insert into book (owner, title, author, year) values ("user2", "The Warren Buffett Way", "Robert G. Hagstrom/Bill Miller/Kenneth L. Fisher", 2005);
insert into book (owner, title, author, year) values ("user1", "The Warren Buffett CEO: Secrets from the Berkshire Hathaway Managers", "Robert P. Miles/Tom Osborne", 2003);
insert into book (owner, title, author, year) values ("user2", "Monkey Business: True Story of the Scopes Trial", "Marvin N. Olasky/John R. Perry", 2005);
insert into book (owner, title, author, year) values ("user2", "Junie B. Jones and a Little Monkey Business (Junie B. Jones  #2)", "Barbara Park/Denise Brunkus", 1993);
insert into book (owner, title, author, year) values ("user2", "Monkey Business", "Sarah Mlynowski", 2004);
insert into book (owner, title, author, year) values ("user1", "Liar's Poker", "Michael   Lewis", 1990);
insert into book (owner, title, author, year) values ("user1", "Liar's Poker: A Harry Garnish Mystery", "Frank McConnell", 1993);
insert into book (owner, title, author, year) values ("user2", "Risotto: 30 Simply Delicious Vegetarian Recipes from an Italian Kitchen", "Ursula Ferrigno/Jason Lowe/Maxine  Clark", 2001);
insert into book (owner, title, author, year) values ("user2", "Giada's Family Dinners", "Giada De Laurentiis/Victoria Pearson", 2006);
insert into book (owner, title, author, year) values ("user2", "Everyday Italian: 125 Simple and Delicious Recipes", "Giada De Laurentiis", 2005);
insert into book (owner, title, author, year) values ("user2", "Everyday Pasta", "Giada De Laurentiis/Victoria Pearson", 2007);
insert into book (owner, title, author, year) values ("user1", "Tyler's Ultimate: Brilliant Simple Food to Make Any Time", "Tyler Florence/Petrina Tinslay", 2006);
insert into book (owner, title, author, year) values ("user2", "Tyler Florence's Real Kitchen: An Indespensible Guide for Anybody Who Likes to Cook", "Tyler Florence/JoAnn Cianciulli/Bill Bettencourt/Bobby Flay", 2003);
insert into book (owner, title, author, year) values ("user2", "Eat This Book: Cooking with Global Fresh Flavors", "Tyler Florence/Petrina Tinslay", 2004);
insert into book (owner, title, author, year) values ("user1", "Freakonomics: A Rogue Economist Explores the Hidden Side of Everything", "Steven D. Levitt/Stephen J. Dubner", 2006);
insert into book (owner, title, author, year) values ("user1", "Freakonomics: Un economista políticamente incorrecto explora el lado oculto de lo que nos afecta", "Steven D. Levitt/Stephen J. Dubner", 2006);
insert into book (owner, title, author, year) values ("user1", "Freakonomics: A Rogue Economist Explores the Hidden Side of Everything", "Steven D. Levitt/Stephen J. Dubner", 2006);
insert into book (owner, title, author, year) values ("user2", "The Last Assassin (John Rain  #5)", "Barry Eisler", 2006);
insert into book (owner, title, author, year) values ("user2", "Life of Pi", "Yann Martel", 2004);
insert into book (owner, title, author, year) values ("user2", "L'Histoire de Pi", "Yann Martel/Nicole Martel/Emile Martel", 2005);
insert into book (owner, title, author, year) values ("user1", "Shadows and Wind: A View of Modern Vietnam", "Robert Templer", 1999);
insert into book (owner, title, author, year) values ("user1", "A Million Little Pieces", "James Frey", 2005);
insert into book (owner, title, author, year) values ("user1", "A Million Little Pieces of Feces", "Python Bonkers", 2006);
insert into book (owner, title, author, year) values ("user2", "A Million Little Lies", "James Pinocchio/Pablo Fenjves", 2006);
insert into book (owner, title, author, year) values ("user1", "The Leadership Challenge", "James M. Kouzes/Barry Z. Posner", 2003);
insert into book (owner, title, author, year) values ("user2", "Lincoln on Leadership: Executive Strategies for Tough Times", "Donald T. Phillips", 1993);
insert into book (owner, title, author, year) values ("user1", "Leadership in Organizations", "Gary Yukl", 2005);
insert into book (owner, title, author, year) values ("user2", "Leadership", "Rudolph W. Giuliani", 2002);
insert into book (owner, title, author, year) values ("user1", "Men Are from Mars  Women Are from Venus", "John Gray", 2012);
insert into book (owner, title, author, year) values ("user1", "Mars and Venus Book of Days: 365 Inspriations to Enrich Your Relationships", "John Gray", 1998);
insert into book (owner, title, author, year) values ("user1", "Men Are from Mars  Women Are from Venus", "John Gray", 2007);
insert into book (owner, title, author, year) values ("user2", "How to Succeed with Women", "Ron  Louis/David Copeland", 1998);
insert into book (owner, title, author, year) values ("user1", "The Clan of the Cave Bear (Earth's Children  #1)", "Jean M. Auel", 2002);
insert into book (owner, title, author, year) values ("user1", "The Clan of the Cave Bear (Earth's Children  #1)", "Jean M. Auel", 1980);
insert into book (owner, title, author, year) values ("user1", "Moneyball: The Art of Winning an Unfair Game", "Michael   Lewis", 2004);
insert into book (owner, title, author, year) values ("user2", "Juiced Official Strategy Guide", "Doug Walsh", 2005);
insert into book (owner, title, author, year) values ("user2", "The 48 Laws of Power", "Robert Greene/Joost Elffers", 2000);
insert into book (owner, title, author, year) values ("user2", "Gates of Fire", "Steven Pressfield", 2005);
insert into book (owner, title, author, year) values ("user1", "Fire Sea (The Death Gate Cycle  #3)", "Margaret Weis/Tracy Hickman", 1992);
insert into book (owner, title, author, year) values ("user2", "The Gate of Fire (Oath Of Empire Book Two)", "Thomas Harlan", 2001);
insert into book (owner, title, author, year) values ("user2", "The Afghan Campaign", "Steven Pressfield", 2006);
insert into book (owner, title, author, year) values ("user1", "Tides of War", "Steven Pressfield", 2001);
insert into book (owner, title, author, year) values ("user1", "Last of the Amazons", "Steven Pressfield", 2003);
insert into book (owner, title, author, year) values ("user2", "The War of Art: Break Through the Blocks & Win Your Inner Creative Battles", "Steven Pressfield/Robert McKee", 2003);
insert into book (owner, title, author, year) values ("user1", "Gita on the Green", "Stephen J. Rosen/Steven Pressfield", 2002);
insert into book (owner, title, author, year) values ("user2", "Blood Stripes: The Grunt's View of the War in Iraq", "David J. Danelo/Steven Pressfield", 2006);
insert into book (owner, title, author, year) values ("user1", "Phaedrus and Letters VII and VIII", "Plato/Walter Hamilton", 1973);
insert into book (owner, title, author, year) values ("user1", "Phaedrus", "Plato/Robin Waterfield", 2003);
insert into book (owner, title, author, year) values ("user1", "Phaedrus", "Plato/C.J. Rowe", 2005);
insert into book (owner, title, author, year) values ("user1", "Lysis/Phaedrus/Symposium: Plato on Homosexuality", "Plato/Benjamin Jowett", 1991);
insert into book (owner, title, author, year) values ("user1", "Enthusiasm and Divine Madness", "Josef Pieper/Richard Winston/Clara Winston", 2019);
insert into book (owner, title, author, year) values ("user2", "On Love: Lysis/Symposium/Phaedrus/Alcibiades/Selections from Republic & Laws", "Plato/C.D.C. Reeve", 2006);
insert into book (owner, title, author, year) values ("user2", "Gorgias/Phaedrus (Agora)", "Plato/James H. Nichols Jr.", 1998);
insert into book (owner, title, author, year) values ("user1", "Statesman", "Plato/C.J. Rowe", 1999);
insert into book (owner, title, author, year) values ("user2", "Gorgias", "Plato/Walter Hamilton/Chris Emlyn-Jones", 2004);
insert into book (owner, title, author, year) values ("user1", "The Histories", "Herodotus/Aubrey de Sélincourt/John M. Marincola", 2003);
insert into book (owner, title, author, year) values ("user2", "The Histories", "Herodotus/Aubrey de Sélincourt/John M. Marincola", 1954);
insert into book (owner, title, author, year) values ("user2", "The History (Great Minds)", "Herodotus/Henry Francis Cary", 1992);
insert into book (owner, title, author, year) values ("user1", "The Histories", "Herodotus/Carolyn Dewald/Robin Waterfield", 1998);
insert into book (owner, title, author, year) values ("user1", "The Histories", "Herodotus/Aubrey de Sélincourt/Andrew Robert Burn", 1970);
insert into book (owner, title, author, year) values ("user2", "The Histories", "Herodotus/Jennifer Tolbert Roberts/Walter Blanco", 1992);
insert into book (owner, title, author, year) values ("user2", "The Histories", "Herodotus/Edward Henry Blakeney/George Rawlinson/Rosalind Thomas", 1997);
insert into book (owner, title, author, year) values ("user2", "The History", "Herodotus/Peter Grene", 1987);
insert into book (owner, title, author, year) values ("user2", "The Iliad", "Homer/Robert Fagles/Bernard Knox", 1999);
insert into book (owner, title, author, year) values ("user2", "Iliad", "Homer/Stanley Lombardo/Sheila Murnaghan", 1997);
insert into book (owner, title, author, year) values ("user1", "The Iliad", "Homer/Robert Fitzgerald/Andrew Ford", 2004);
insert into book (owner, title, author, year) values ("user1", "The Iliad/The Odyssey", "Homer/Robert Fagles/Bernard Knox", 1999);
insert into book (owner, title, author, year) values ("user1", "The Iliad", "Homer/E.V. Rieu/Peter Jones/D.C.H. Rieu", 2003);
insert into book (owner, title, author, year) values ("user2", "The Iliad", "Homer/W.H.D. Rouse", 1999);
insert into book (owner, title, author, year) values ("user2", "The Essential Iliad", "Homer/Sheila Murnaghan/Stanley Lombardo", 2000);
insert into book (owner, title, author, year) values ("user2", "The Odyssey", "Homer/Robert Fagles/Bernard Knox", 2006);
insert into book (owner, title, author, year) values ("user2", "The Odyssey", "Homer/Robert Fitzgerald/D.S. Carne-Ross", 1998);
insert into book (owner, title, author, year) values ("user1", "The Odyssey", "Homer/Richmond Lattimore", 1999);
insert into book (owner, title, author, year) values ("user1", "The Odyssey", "Homer/E.V. Rieu/Peter Jones/D.C.H. Rieu", 2003);
insert into book (owner, title, author, year) values ("user1", "The Odyssey", "Homer/W.H.D. Rouse", 1999);
insert into book (owner, title, author, year) values ("user1", "Aeneid: Selections from Books 1  2  4  6  10  12", "Virgil/Barbara Weiden Boyd", 2001);
insert into book (owner, title, author, year) values ("user1", "Eclogues. Georgics. Aeneid: Books 1-6", "Virgil/Henry Rushton Fairclough/G.P. Goold", 1999);
insert into book (owner, title, author, year) values ("user2", "City Eclogue", "Ed Roberson", 2006);
insert into book (owner, title, author, year) values ("user2", "The Eclogues and The Georgics", "Virgil/Cecil Day-Lewis", 1999);
insert into book (owner, title, author, year) values ("user1", "Paul Kirk's Championship Barbecue Sauces: 175 Make-Your-Own Sauces  Marinades  Dry Rubs  Wet Rubs  Mops and Salsas", "Paul  Kirk", 1997);
insert into book (owner, title, author, year) values ("user2", "The Complete Pelican Shakespeare", "William Shakespeare/Stephen Orgel/A.R. Braunmuller", 2002);
insert into book (owner, title, author, year) values ("user1", "The Complete Works", "William Shakespeare", 1991);
insert into book (owner, title, author, year) values ("user2", "Hamlet", "William Shakespeare/Harold Bloom/Rex Gibson", 2005);
insert into book (owner, title, author, year) values ("user1", "The Compleat Works of Wllm Shkspr (abridged)", "Reduced Shakespeare Company/Adam Long/Daniel Singer/Jess Winfield", 1994);
insert into book (owner, title, author, year) values ("user1", "The Pilgrimage: A Contemporary Quest for Ancient Wisdom", "Paulo Coelho/Alan R. Clarke", 1995);
insert into book (owner, title, author, year) values ("user1", "The Valkyries", "Paulo Coelho/Alan R. Clarke", 1996);
insert into book (owner, title, author, year) values ("user1", "Warrior of the Light", "Paulo Coelho", 2004);
insert into book (owner, title, author, year) values ("user1", "The Zahir", "Paulo Coelho/Margaret Jull Costa", 2006);
insert into book (owner, title, author, year) values ("user1", "By the River Piedra I Sat Down and Wept", "Paulo Coelho/Alan R. Clarke", 2006);
insert into book (owner, title, author, year) values ("user2", "The Fifth Mountain", "Paulo Coelho/Clifford E. Landers", 2000);
insert into book (owner, title, author, year) values ("user1", "Veronika Decides to Die", "Paulo Coelho/Margaret Jull Costa/Kâmuran Şipal", 2006);
insert into book (owner, title, author, year) values ("user1", "Hamlet", "William Shakespeare/Stephen Orgel/A.R. Braunmuller", 2001);
insert into book (owner, title, author, year) values ("user1", "Cliffs Notes on Shakespeare's Hamlet", "Carla Lynn Stockton", 2000);
insert into book (owner, title, author, year) values ("user2", "Shakespeare's Hamlet", "William Shakespeare/Terri Mategrano", 2000);
insert into book (owner, title, author, year) values ("user1", "Hamlet's Mill: An Essay Investigating the Origins of Human Knowledge and Its Transmission Through Myth", "Giorgio De Santillana/Hertha Von Dechend", 2015);
insert into book (owner, title, author, year) values ("user1", "History of the Peloponnesian War: Bk. 1-2", "Thucydides/C.F. Smith", 1919);
insert into book (owner, title, author, year) values ("user2", "On Justice  Power and Human Nature: Selections from The History of the Peloponnesian War", "Thucydides/Paul Woodruff", 1993);
insert into book (owner, title, author, year) values ("user2", "History of the Peloponnesian War: Bk. 5-6", "Thucydides/C.F. Smith", 1921);
insert into book (owner, title, author, year) values ("user2", "The Peloponnesian War", "Thucydides/Steven Lattimore", 1998);
insert into book (owner, title, author, year) values ("user1", "The Peloponnesian War: A New Translation  Backgrounds  Interpretations", "Thucydides/Jennifer Tolbert Roberts/Walter Blanco", 1998);
insert into book (owner, title, author, year) values ("user1", "History of the Peloponnesian War  Bk. 7-8", "Thucydides/C.F. Smith", 1923);
insert into book (owner, title, author, year) values ("user2", "Thucydides  Book 6 Commentary", "Cynthia W. Shelmerdine", 1989);
insert into book (owner, title, author, year) values ("user2", "Euripides I: Alcestis / The Medea / The Heracleidae / Hippolytus", "Euripides/Richmond Lattimore/David Grene/Rex Warner/Ralph Gladstone", 1955);
insert into book (owner, title, author, year) values ("user1", "Euripides V: Electra / The Phoenician Women / The Bacchae", "Euripides/David Grene/Richmond Lattimore/Emily Townsend Vermeule/Elizabeth Wyckoff/William Arrowsmith", 1969);
insert into book (owner, title, author, year) values ("user1", "Euripides IV: Rhesus / The Suppliant Women / Orestes / Iphigenia in Aulis", "Euripides/David Grene/Richmond Lattimore/William Arrowsmith/Frank William Jones/Charles R. Walker", 1968);
insert into book (owner, title, author, year) values ("user2", "Grief Lessons: Four Plays by Euripides", "Anne Carson/Euripides", 2006);
insert into book (owner, title, author, year) values ("user2", "Ten Plays", "Euripides/Moses Hadas/John Maclean", 1990);
insert into book (owner, title, author, year) values ("user2", "Euripides III: Hecuba / Andromache / The Trojan Women / Ion (Complete Greek Tragedies  #7)", "Euripides/David Grene/Richmond Lattimore/William Arrowsmith/John Frederick Nims/Ronald Frederick Willetts", 1992);
insert into book (owner, title, author, year) values ("user1", "Euripides II: The Cyclops / Heracles / Iphigenia in Tauris / Helen", "Euripides/David Grene/Richmond Lattimore/Witter Bynner/William Arrowsmith", 2002);
insert into book (owner, title, author, year) values ("user2", "Medea and Other Plays", "Euripides/John Davie/Richard Rutherford", 2003);
insert into book (owner, title, author, year) values ("user2", "Cyclops / Alcestis / Medea", "Euripides/David Kovacs", 1994);
insert into book (owner, title, author, year) values ("user2", "Medea", "Euripides/Donald J. Mastronarde", 2002);
insert into book (owner, title, author, year) values ("user1", "The Bacchae and Other Plays", "Euripides/John Davie/Richard Rutherford", 2006);
insert into book (owner, title, author, year) values ("user1", "Bakkhai", "Euripides/Reginald Gibbons/Peter H. Burian", 2001);
insert into book (owner, title, author, year) values ("user2", "Plays 1: Medea/The Phoenician Women/Bacchae", "Euripides/David Thompson/J. Michael Walton", 2000);
insert into book (owner, title, author, year) values ("user2", "The Trojan Women and Hippolytus", "Euripides", 2002);
insert into book (owner, title, author, year) values ("user1", "The Bacchae of Euripides: A Communion Rite", "Wole Soyinka", 2004);
insert into book (owner, title, author, year) values ("user1", "Orestes and Other Plays", "Euripides/James Morwood/Robin Waterfield", 2001);
insert into book (owner, title, author, year) values ("user1", "Children of Heracles / Hippolytus / Andromache / Hecuba", "Euripides/David Kovacs", 1995);
insert into book (owner, title, author, year) values ("user2", "Alcestis", "Euripides/William Arrowsmith", 1990);
insert into book (owner, title, author, year) values ("user1", "Suppliant Women / Electra / Heracles", "Euripides/David Kovacs", 1998);
insert into book (owner, title, author, year) values ("user1", "Medea", "Euripides/Georgia Ann Machemer/Michael   Collier", 2006);
insert into book (owner, title, author, year) values ("user1", "Euripides: Medea", "William Allan", 2002);
insert into book (owner, title, author, year) values ("user1", "CliffsNotes on Euripides' Medea and Electra", "Robert J. Milch", 1965);
insert into book (owner, title, author, year) values ("user2", "Trojan Women / Iphigenia Among the Taurians / Ion", "Euripides/David Kovacs", 1999);
